server_names = ['odohtarget', 'odohrelay']
listen_addresses = ['0.0.0.0:53']
log_files_max_size = 0

[query_log]
# file = '/var/log/query.log'
file = '/dev/stdout'

[static]
  [static.'odohtarget']
  # odoh.cloudflare-dns.com
  stamp = 'sdns://BQcAAAAAAAAAF29kb2guY2xvdWRmbGFyZS1kbnMuY29tCi9kbnMtcXVlcnk'

  [static.'odohrelay']
  # odoh1.surfdomainen.nl
  stamp = 'sdns://hQcAAAAAAAAACjE0NS4wLjYuNTMgEbEC5rH2PlKJhNYCXzKxOCQfyIu9dRlXTXDJgy1T4egVb2RvaDEuc3VyZmRvbWVpbmVuLm5sBi9wcm94eQ'

[anonymized_dns]
routes = [
    { server_name='odohtarget', via=['odohrelay'] }
]
