#server_names = ['odohtarget-ms', 'odohrelay-ms']
# listen_addresses = ['127.0.0.1:53', '[::1]:53']
listen_addresses = ['0.0.0.0:53']
# bootstrap_resolvers = ['1.1.1.1:53', '9.9.9.9:53', '8.8.8.8:53']
bootstrap_resolvers = ['1.1.1.1:53']
ignore_system_dns = true
keepalive = 30
ipv4_servers = true
ipv6_servers = false
dnscrypt_servers = false
doh_servers = false
odoh_servers = true
log_files_max_size = 0

# Enable in case you want to load the public odoh server list
# If enabled, enable the "pairs" in the routes
# [sources]
#   [sources.'odoh']
#   urls = ['https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v3/odoh.md', 'https://download.dnscrypt.info/resolvers-list/v3/odoh.md']
#   minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
#   cache_file = 'odoh.md'

# Enable logging
[query_log]
#  file = '/var/log/query.log'
file = '/dev/stdout'

# Static configured odoh target and relay servers
# You can only enable 1 stamp per static entry
[static]
  # [static.'odohtarget-cf']
  # cloudflare-dns.com
  # stamp = 'sdns://BQcAAAAAAAAAEmNsb3VkZmxhcmUtZG5zLmNvbQovZG5zLXF1ZXJ5'
  # odoh.cloudflare-dns.com
  # stamp = 'sdns://BQcAAAAAAAAAF29kb2guY2xvdWRmbGFyZS1kbnMuY29tCi9kbnMtcXVlcnk'
  # [static.'odohrelay-cf']
  # proxy.odoh.cloudflare-dns.com
  # stamp = 'sdns://hQcAAAAAAAAAAAAdcHJveHkub2RvaC5jbG91ZGZsYXJlLWRucy5jb20GL3Byb3h5'
  # odoh1.surfdomeinen.nl
  # stamp = 'sdns://hQcAAAAAAAAACjE0NS4wLjYuNTMgEbEC5rH2PlKJhNYCXzKxOCQfyIu9dRlXTXDJgy1T4egVb2RvaDEuc3VyZmRvbWVpbmVuLm5sBi9wcm94eQ'

  # [static.'odohtarget-co']
  # odoh.crypto.sx
  # stamp = 'sdns://BQcAAAAAAAAADm9kb2guY3J5cHRvLnN4Ci9kbnMtcXVlcnk'
  # [static.'odohrelay-co']
  # odoh-relay.edgecompute.app
  # stamp = 'sdns://hQcAAAAAAAAAACCi3jNJDEdtNW4tvHN8J3lpIklSa2Wrj7qaNCgEgci9_BpvZG9oLXJlbGF5LmVkZ2Vjb21wdXRlLmFwcAEv'

  [static.'odohtarget-ms']
  # doh.marco.cx
  stamp = 'sdns://BQcAAAAAAAAADGRvaC5tYXJjby5jeAovZG5zLXF1ZXJ5'
  [static.'odohrelay-ms']
  # odoh.marco.cx
  stamp = 'sdns://hQcAAAAAAAAAAAANb2RvaC5tYXJjby5jeAYvcHJveHk'

[anonymized_dns]
  routes = [
    # Pairs from the sources section
    # Enable or add them, after you have enabled "[sources.'odoh']" in the "sources" section above
    #
    # Target = Cloudflare ## Relay = surf.nl
    # { server_name='odoh-cloudflare', via=['odohrelay-surf'] },
    # Target = crypto.sx ## Relay = crypto.sx
    # { server_name='odoh-crypto-sx', via=['odohrelay-crypto-sx'] },

    # Pairs from the static section
    # Enable or add them depending on what you have in the "static" section above
    #
    # Target = Cloudflare ## Relay = Cloudflare
    # { server_name='odohtarget-cf', via=['odohrelay-cf'] },
    # Target = crypto.sx ## Relay = crypto.sx
    # { server_name='odohtarget-co', via=['odohrelay-co'] },
    # Target = Marco-VT ## Relay = Marco-OC
    { server_name='odohtarget-ms', via=['odohrelay-ms'] }
  ]
